trigger:
  branches:
    include:
    - feature/*

pool:
  vmImage: 'windows-latest'

steps:
- script: echo 'Iniciando el build...'
  displayName: 'Iniciando el build'

- task: UseDotNet@2
  inputs:
    version: '6.x'
  displayName: 'Usando .NET 6'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  displayName: 'Restaurando paquetes NuGet'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
  displayName: 'Compilando el proyecto'

- script: |
    if [ $? -ne 0 ]; then
      echo 'El build falló, se detiene el pipeline.'
      exit 1
    fi
  displayName: 'Comprobando errores de compilación'

- script: echo 'Continuando con el proceso...'
  displayName: 'Continuando con el proceso'

- script: git push
  displayName: 'Haciendo commit de los cambios'
