// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/Cliente.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EntryPoints.GRPc.Protos {

  /// <summary>Holder for reflection information generated from Proto/Cliente.proto</summary>
  public static partial class ClienteReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/Cliente.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClienteReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQcm90by9DbGllbnRlLnByb3RvEghjbGllbnRlcxoZZ29vZ2xlL3Byb3Rv",
            "YnVmL2FueS5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90",
            "byJLChNDcmVhclVzdWFyaW9SZXF1ZXN0EhYKDm5vbWJyZUNvbXBsZXRvGAEg",
            "ASgJEhwKA3JvbBgCIAEoDjIPLmNsaWVudGVzLlJvbGVzIqMBChNDcmVhckNs",
            "aWVudGVSZXF1ZXN0Ei8KC2ZlY2hhQWN0dWFsGAEgASgLMhouZ29vZ2xlLnBy",
            "b3RvYnVmLlRpbWVzdGFtcBIcChRudW1lcm9JZGVudGlmaWNhY2lvbhgCIAEo",
            "CRIPCgdub21icmVzGAMgASgJEhEKCWFwZWxsaWRvcxgEIAEoCRIZChFjb3Jy",
            "ZW9FbGVjdHJvbmljbxgFIAEoCSolCgVSb2xlcxIJCgVBZG1pbhAAEhEKDVRy",
            "YW5zYWNjaW9uYWwQAUIaqgIXRW50cnlQb2ludHMuR1JQYy5Qcm90b3NiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::EntryPoints.GRPc.Protos.Roles), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.CrearUsuarioRequest), global::EntryPoints.GRPc.Protos.CrearUsuarioRequest.Parser, new[]{ "NombreCompleto", "Rol" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.CrearClienteRequest), global::EntryPoints.GRPc.Protos.CrearClienteRequest.Parser, new[]{ "FechaActual", "NumeroIdentificacion", "Nombres", "Apellidos", "CorreoElectronico" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Roles {
    [pbr::OriginalName("Admin")] Admin = 0,
    [pbr::OriginalName("Transaccional")] Transaccional = 1,
  }

  #endregion

  #region Messages
  /// <summary>
  /// Requests
  /// </summary>
  public sealed partial class CrearUsuarioRequest : pb::IMessage<CrearUsuarioRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CrearUsuarioRequest> _parser = new pb::MessageParser<CrearUsuarioRequest>(() => new CrearUsuarioRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CrearUsuarioRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClienteReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearUsuarioRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearUsuarioRequest(CrearUsuarioRequest other) : this() {
      nombreCompleto_ = other.nombreCompleto_;
      rol_ = other.rol_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearUsuarioRequest Clone() {
      return new CrearUsuarioRequest(this);
    }

    /// <summary>Field number for the "nombreCompleto" field.</summary>
    public const int NombreCompletoFieldNumber = 1;
    private string nombreCompleto_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NombreCompleto {
      get { return nombreCompleto_; }
      set {
        nombreCompleto_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rol" field.</summary>
    public const int RolFieldNumber = 2;
    private global::EntryPoints.GRPc.Protos.Roles rol_ = global::EntryPoints.GRPc.Protos.Roles.Admin;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EntryPoints.GRPc.Protos.Roles Rol {
      get { return rol_; }
      set {
        rol_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CrearUsuarioRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CrearUsuarioRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NombreCompleto != other.NombreCompleto) return false;
      if (Rol != other.Rol) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NombreCompleto.Length != 0) hash ^= NombreCompleto.GetHashCode();
      if (Rol != global::EntryPoints.GRPc.Protos.Roles.Admin) hash ^= Rol.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NombreCompleto.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NombreCompleto);
      }
      if (Rol != global::EntryPoints.GRPc.Protos.Roles.Admin) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Rol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NombreCompleto.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NombreCompleto);
      }
      if (Rol != global::EntryPoints.GRPc.Protos.Roles.Admin) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Rol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NombreCompleto.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NombreCompleto);
      }
      if (Rol != global::EntryPoints.GRPc.Protos.Roles.Admin) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Rol);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CrearUsuarioRequest other) {
      if (other == null) {
        return;
      }
      if (other.NombreCompleto.Length != 0) {
        NombreCompleto = other.NombreCompleto;
      }
      if (other.Rol != global::EntryPoints.GRPc.Protos.Roles.Admin) {
        Rol = other.Rol;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            NombreCompleto = input.ReadString();
            break;
          }
          case 16: {
            Rol = (global::EntryPoints.GRPc.Protos.Roles) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            NombreCompleto = input.ReadString();
            break;
          }
          case 16: {
            Rol = (global::EntryPoints.GRPc.Protos.Roles) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CrearClienteRequest : pb::IMessage<CrearClienteRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CrearClienteRequest> _parser = new pb::MessageParser<CrearClienteRequest>(() => new CrearClienteRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CrearClienteRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClienteReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearClienteRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearClienteRequest(CrearClienteRequest other) : this() {
      fechaActual_ = other.fechaActual_ != null ? other.fechaActual_.Clone() : null;
      numeroIdentificacion_ = other.numeroIdentificacion_;
      nombres_ = other.nombres_;
      apellidos_ = other.apellidos_;
      correoElectronico_ = other.correoElectronico_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearClienteRequest Clone() {
      return new CrearClienteRequest(this);
    }

    /// <summary>Field number for the "fechaActual" field.</summary>
    public const int FechaActualFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp fechaActual_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp FechaActual {
      get { return fechaActual_; }
      set {
        fechaActual_ = value;
      }
    }

    /// <summary>Field number for the "numeroIdentificacion" field.</summary>
    public const int NumeroIdentificacionFieldNumber = 2;
    private string numeroIdentificacion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumeroIdentificacion {
      get { return numeroIdentificacion_; }
      set {
        numeroIdentificacion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nombres" field.</summary>
    public const int NombresFieldNumber = 3;
    private string nombres_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nombres {
      get { return nombres_; }
      set {
        nombres_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "apellidos" field.</summary>
    public const int ApellidosFieldNumber = 4;
    private string apellidos_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Apellidos {
      get { return apellidos_; }
      set {
        apellidos_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "correoElectronico" field.</summary>
    public const int CorreoElectronicoFieldNumber = 5;
    private string correoElectronico_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CorreoElectronico {
      get { return correoElectronico_; }
      set {
        correoElectronico_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CrearClienteRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CrearClienteRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FechaActual, other.FechaActual)) return false;
      if (NumeroIdentificacion != other.NumeroIdentificacion) return false;
      if (Nombres != other.Nombres) return false;
      if (Apellidos != other.Apellidos) return false;
      if (CorreoElectronico != other.CorreoElectronico) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (fechaActual_ != null) hash ^= FechaActual.GetHashCode();
      if (NumeroIdentificacion.Length != 0) hash ^= NumeroIdentificacion.GetHashCode();
      if (Nombres.Length != 0) hash ^= Nombres.GetHashCode();
      if (Apellidos.Length != 0) hash ^= Apellidos.GetHashCode();
      if (CorreoElectronico.Length != 0) hash ^= CorreoElectronico.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (fechaActual_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FechaActual);
      }
      if (NumeroIdentificacion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeroIdentificacion);
      }
      if (Nombres.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nombres);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Apellidos);
      }
      if (CorreoElectronico.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CorreoElectronico);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (fechaActual_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FechaActual);
      }
      if (NumeroIdentificacion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeroIdentificacion);
      }
      if (Nombres.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nombres);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Apellidos);
      }
      if (CorreoElectronico.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CorreoElectronico);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (fechaActual_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FechaActual);
      }
      if (NumeroIdentificacion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeroIdentificacion);
      }
      if (Nombres.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nombres);
      }
      if (Apellidos.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Apellidos);
      }
      if (CorreoElectronico.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CorreoElectronico);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CrearClienteRequest other) {
      if (other == null) {
        return;
      }
      if (other.fechaActual_ != null) {
        if (fechaActual_ == null) {
          FechaActual = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        FechaActual.MergeFrom(other.FechaActual);
      }
      if (other.NumeroIdentificacion.Length != 0) {
        NumeroIdentificacion = other.NumeroIdentificacion;
      }
      if (other.Nombres.Length != 0) {
        Nombres = other.Nombres;
      }
      if (other.Apellidos.Length != 0) {
        Apellidos = other.Apellidos;
      }
      if (other.CorreoElectronico.Length != 0) {
        CorreoElectronico = other.CorreoElectronico;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (fechaActual_ == null) {
              FechaActual = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(FechaActual);
            break;
          }
          case 18: {
            NumeroIdentificacion = input.ReadString();
            break;
          }
          case 26: {
            Nombres = input.ReadString();
            break;
          }
          case 34: {
            Apellidos = input.ReadString();
            break;
          }
          case 42: {
            CorreoElectronico = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (fechaActual_ == null) {
              FechaActual = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(FechaActual);
            break;
          }
          case 18: {
            NumeroIdentificacion = input.ReadString();
            break;
          }
          case 26: {
            Nombres = input.ReadString();
            break;
          }
          case 34: {
            Apellidos = input.ReadString();
            break;
          }
          case 42: {
            CorreoElectronico = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
