// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/Cliente.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EntryPoints.GRPc.Protos {

  /// <summary>Holder for reflection information generated from Proto/Cliente.proto</summary>
  public static partial class ClienteReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/Cliente.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClienteReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQcm90by9DbGllbnRlLnByb3RvEghjbGllbnRlcyI6ChNDcmVhclVzdWFy",
            "aW9SZXF1ZXN0EhYKDm5vbWJyZUNvbXBsZXRvGAEgASgJEgsKA3JvbBgCIAEo",
            "BSI/CgxVc3VhcmlvUHJvdG8SCgoCaWQYASABKAkSFgoObm9tYnJlQ29tcGxl",
            "dG8YAiABKAkSCwoDcm9sGAMgASgFIlYKE0NsaWVudGVDcmVhclJlcXVlc3QS",
            "EQoJSWRVc3VhcmlvGAEgASgJEiwKB0NsaWVudGUYAiABKAsyGy5jbGllbnRl",
            "cy5DcmVhckNsaWVudGVQcm90byLfAgoMQ2xpZW50ZVByb3RvEhMKC0ZlY2hh",
            "QWN0dWFsGAEgASgJEgoKAklkGAIgASgJEhoKElRpcG9JZGVudGlmaWNhY2lv",
            "bhgDIAEoBRIcChROdW1lcm9JZGVudGlmaWNhY2lvbhgEIAEoCRIPCgdOb21i",
            "cmVzGAUgASgJEhEKCUFwZWxsaWRvcxgGIAEoCRIZChFDb3JyZW9FbGVjdHJv",
            "bmljbxgHIAEoCRIXCg9GZWNoYU5hY2ltaWVudG8YCCABKAkSFQoNRmVjaGFD",
            "cmVhY2lvbhgJIAEoCRI+ChhoaXN0b3JpYWxBY3R1YWxpemFjaW9uZXMYCiAD",
            "KAsyHC5jbGllbnRlcy5BY3R1YWxpemFjaW9uUHJvdG8SFgoORXN0YUhhYmls",
            "aXRhZG8YCyABKAgSGgoSVGllbmVEZXVkYXNBY3RpdmFzGAwgASgIEhEKCVBy",
            "b2R1Y3RvcxgNIAMoCSKlAQoRQ3JlYXJDbGllbnRlUHJvdG8SGgoSVGlwb0lk",
            "ZW50aWZpY2FjaW9uGAEgASgFEhwKFE51bWVyb0lkZW50aWZpY2FjaW9uGAIg",
            "ASgJEg8KB05vbWJyZXMYAyABKAkSEQoJQXBlbGxpZG9zGAQgASgJEhkKEUNv",
            "cnJlb0VsZWN0cm9uaWNvGAUgASgJEhcKD0ZlY2hhTmFjaW1pZW50bxgGIAEo",
            "CSJzChJBY3R1YWxpemFjaW9uUHJvdG8SGQoRdGlwb0FjdHVhbGl6YWNpb24Y",
            "ASABKAUSMwoTdXN1YXJpb01vZGlmaWNhY2lvbhgCIAEoCzIWLmNsaWVudGVz",
            "LlVzdWFyaW9Qcm90bxINCgVmZWNoYRgDIAEoCTKfAQoPQ2xpZW50ZVNlcnZp",
            "Y2VzEkUKDENyZWFyVXN1YXJpbxIdLmNsaWVudGVzLkNyZWFyVXN1YXJpb1Jl",
            "cXVlc3QaFi5jbGllbnRlcy5Vc3VhcmlvUHJvdG8SRQoMQ3JlYXJDbGllbnRl",
            "Eh0uY2xpZW50ZXMuQ2xpZW50ZUNyZWFyUmVxdWVzdBoWLmNsaWVudGVzLkNs",
            "aWVudGVQcm90b0IaqgIXRW50cnlQb2ludHMuR1JQYy5Qcm90b3NiBnByb3Rv",
            "Mw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.CrearUsuarioRequest), global::EntryPoints.GRPc.Protos.CrearUsuarioRequest.Parser, new[]{ "NombreCompleto", "Rol" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.UsuarioProto), global::EntryPoints.GRPc.Protos.UsuarioProto.Parser, new[]{ "Id", "NombreCompleto", "Rol" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.ClienteCrearRequest), global::EntryPoints.GRPc.Protos.ClienteCrearRequest.Parser, new[]{ "IdUsuario", "Cliente" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.ClienteProto), global::EntryPoints.GRPc.Protos.ClienteProto.Parser, new[]{ "FechaActual", "Id", "TipoIdentificacion", "NumeroIdentificacion", "Nombres", "Apellidos", "CorreoElectronico", "FechaNacimiento", "FechaCreacion", "HistorialActualizaciones", "EstaHabilitado", "TieneDeudasActivas", "Productos" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.CrearClienteProto), global::EntryPoints.GRPc.Protos.CrearClienteProto.Parser, new[]{ "TipoIdentificacion", "NumeroIdentificacion", "Nombres", "Apellidos", "CorreoElectronico", "FechaNacimiento" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EntryPoints.GRPc.Protos.ActualizacionProto), global::EntryPoints.GRPc.Protos.ActualizacionProto.Parser, new[]{ "TipoActualizacion", "UsuarioModificacion", "Fecha" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Requests
  /// </summary>
  public sealed partial class CrearUsuarioRequest : pb::IMessage<CrearUsuarioRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CrearUsuarioRequest> _parser = new pb::MessageParser<CrearUsuarioRequest>(() => new CrearUsuarioRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CrearUsuarioRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClienteReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearUsuarioRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearUsuarioRequest(CrearUsuarioRequest other) : this() {
      nombreCompleto_ = other.nombreCompleto_;
      rol_ = other.rol_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearUsuarioRequest Clone() {
      return new CrearUsuarioRequest(this);
    }

    /// <summary>Field number for the "nombreCompleto" field.</summary>
    public const int NombreCompletoFieldNumber = 1;
    private string nombreCompleto_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NombreCompleto {
      get { return nombreCompleto_; }
      set {
        nombreCompleto_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rol" field.</summary>
    public const int RolFieldNumber = 2;
    private int rol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rol {
      get { return rol_; }
      set {
        rol_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CrearUsuarioRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CrearUsuarioRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NombreCompleto != other.NombreCompleto) return false;
      if (Rol != other.Rol) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (NombreCompleto.Length != 0) hash ^= NombreCompleto.GetHashCode();
      if (Rol != 0) hash ^= Rol.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NombreCompleto.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NombreCompleto);
      }
      if (Rol != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NombreCompleto.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NombreCompleto);
      }
      if (Rol != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (NombreCompleto.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NombreCompleto);
      }
      if (Rol != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rol);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CrearUsuarioRequest other) {
      if (other == null) {
        return;
      }
      if (other.NombreCompleto.Length != 0) {
        NombreCompleto = other.NombreCompleto;
      }
      if (other.Rol != 0) {
        Rol = other.Rol;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            NombreCompleto = input.ReadString();
            break;
          }
          case 16: {
            Rol = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            NombreCompleto = input.ReadString();
            break;
          }
          case 16: {
            Rol = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Responses
  /// </summary>
  public sealed partial class UsuarioProto : pb::IMessage<UsuarioProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UsuarioProto> _parser = new pb::MessageParser<UsuarioProto>(() => new UsuarioProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UsuarioProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClienteReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsuarioProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsuarioProto(UsuarioProto other) : this() {
      id_ = other.id_;
      nombreCompleto_ = other.nombreCompleto_;
      rol_ = other.rol_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsuarioProto Clone() {
      return new UsuarioProto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nombreCompleto" field.</summary>
    public const int NombreCompletoFieldNumber = 2;
    private string nombreCompleto_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NombreCompleto {
      get { return nombreCompleto_; }
      set {
        nombreCompleto_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rol" field.</summary>
    public const int RolFieldNumber = 3;
    private int rol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rol {
      get { return rol_; }
      set {
        rol_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UsuarioProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UsuarioProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (NombreCompleto != other.NombreCompleto) return false;
      if (Rol != other.Rol) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (NombreCompleto.Length != 0) hash ^= NombreCompleto.GetHashCode();
      if (Rol != 0) hash ^= Rol.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (NombreCompleto.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NombreCompleto);
      }
      if (Rol != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Rol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (NombreCompleto.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NombreCompleto);
      }
      if (Rol != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Rol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (NombreCompleto.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NombreCompleto);
      }
      if (Rol != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rol);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UsuarioProto other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.NombreCompleto.Length != 0) {
        NombreCompleto = other.NombreCompleto;
      }
      if (other.Rol != 0) {
        Rol = other.Rol;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            NombreCompleto = input.ReadString();
            break;
          }
          case 24: {
            Rol = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            NombreCompleto = input.ReadString();
            break;
          }
          case 24: {
            Rol = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ClienteCrearRequest : pb::IMessage<ClienteCrearRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClienteCrearRequest> _parser = new pb::MessageParser<ClienteCrearRequest>(() => new ClienteCrearRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClienteCrearRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClienteReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClienteCrearRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClienteCrearRequest(ClienteCrearRequest other) : this() {
      idUsuario_ = other.idUsuario_;
      cliente_ = other.cliente_ != null ? other.cliente_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClienteCrearRequest Clone() {
      return new ClienteCrearRequest(this);
    }

    /// <summary>Field number for the "IdUsuario" field.</summary>
    public const int IdUsuarioFieldNumber = 1;
    private string idUsuario_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string IdUsuario {
      get { return idUsuario_; }
      set {
        idUsuario_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Cliente" field.</summary>
    public const int ClienteFieldNumber = 2;
    private global::EntryPoints.GRPc.Protos.CrearClienteProto cliente_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EntryPoints.GRPc.Protos.CrearClienteProto Cliente {
      get { return cliente_; }
      set {
        cliente_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClienteCrearRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClienteCrearRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdUsuario != other.IdUsuario) return false;
      if (!object.Equals(Cliente, other.Cliente)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdUsuario.Length != 0) hash ^= IdUsuario.GetHashCode();
      if (cliente_ != null) hash ^= Cliente.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (IdUsuario.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdUsuario);
      }
      if (cliente_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Cliente);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (IdUsuario.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IdUsuario);
      }
      if (cliente_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Cliente);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdUsuario.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdUsuario);
      }
      if (cliente_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Cliente);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClienteCrearRequest other) {
      if (other == null) {
        return;
      }
      if (other.IdUsuario.Length != 0) {
        IdUsuario = other.IdUsuario;
      }
      if (other.cliente_ != null) {
        if (cliente_ == null) {
          Cliente = new global::EntryPoints.GRPc.Protos.CrearClienteProto();
        }
        Cliente.MergeFrom(other.Cliente);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IdUsuario = input.ReadString();
            break;
          }
          case 18: {
            if (cliente_ == null) {
              Cliente = new global::EntryPoints.GRPc.Protos.CrearClienteProto();
            }
            input.ReadMessage(Cliente);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            IdUsuario = input.ReadString();
            break;
          }
          case 18: {
            if (cliente_ == null) {
              Cliente = new global::EntryPoints.GRPc.Protos.CrearClienteProto();
            }
            input.ReadMessage(Cliente);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Entidad de cliente
  /// </summary>
  public sealed partial class ClienteProto : pb::IMessage<ClienteProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClienteProto> _parser = new pb::MessageParser<ClienteProto>(() => new ClienteProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClienteProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClienteReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClienteProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClienteProto(ClienteProto other) : this() {
      fechaActual_ = other.fechaActual_;
      id_ = other.id_;
      tipoIdentificacion_ = other.tipoIdentificacion_;
      numeroIdentificacion_ = other.numeroIdentificacion_;
      nombres_ = other.nombres_;
      apellidos_ = other.apellidos_;
      correoElectronico_ = other.correoElectronico_;
      fechaNacimiento_ = other.fechaNacimiento_;
      fechaCreacion_ = other.fechaCreacion_;
      historialActualizaciones_ = other.historialActualizaciones_.Clone();
      estaHabilitado_ = other.estaHabilitado_;
      tieneDeudasActivas_ = other.tieneDeudasActivas_;
      productos_ = other.productos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClienteProto Clone() {
      return new ClienteProto(this);
    }

    /// <summary>Field number for the "FechaActual" field.</summary>
    public const int FechaActualFieldNumber = 1;
    private string fechaActual_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FechaActual {
      get { return fechaActual_; }
      set {
        fechaActual_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 2;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TipoIdentificacion" field.</summary>
    public const int TipoIdentificacionFieldNumber = 3;
    private int tipoIdentificacion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TipoIdentificacion {
      get { return tipoIdentificacion_; }
      set {
        tipoIdentificacion_ = value;
      }
    }

    /// <summary>Field number for the "NumeroIdentificacion" field.</summary>
    public const int NumeroIdentificacionFieldNumber = 4;
    private string numeroIdentificacion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumeroIdentificacion {
      get { return numeroIdentificacion_; }
      set {
        numeroIdentificacion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Nombres" field.</summary>
    public const int NombresFieldNumber = 5;
    private string nombres_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nombres {
      get { return nombres_; }
      set {
        nombres_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Apellidos" field.</summary>
    public const int ApellidosFieldNumber = 6;
    private string apellidos_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Apellidos {
      get { return apellidos_; }
      set {
        apellidos_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CorreoElectronico" field.</summary>
    public const int CorreoElectronicoFieldNumber = 7;
    private string correoElectronico_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CorreoElectronico {
      get { return correoElectronico_; }
      set {
        correoElectronico_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FechaNacimiento" field.</summary>
    public const int FechaNacimientoFieldNumber = 8;
    private string fechaNacimiento_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FechaNacimiento {
      get { return fechaNacimiento_; }
      set {
        fechaNacimiento_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FechaCreacion" field.</summary>
    public const int FechaCreacionFieldNumber = 9;
    private string fechaCreacion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FechaCreacion {
      get { return fechaCreacion_; }
      set {
        fechaCreacion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "historialActualizaciones" field.</summary>
    public const int HistorialActualizacionesFieldNumber = 10;
    private static readonly pb::FieldCodec<global::EntryPoints.GRPc.Protos.ActualizacionProto> _repeated_historialActualizaciones_codec
        = pb::FieldCodec.ForMessage(82, global::EntryPoints.GRPc.Protos.ActualizacionProto.Parser);
    private readonly pbc::RepeatedField<global::EntryPoints.GRPc.Protos.ActualizacionProto> historialActualizaciones_ = new pbc::RepeatedField<global::EntryPoints.GRPc.Protos.ActualizacionProto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::EntryPoints.GRPc.Protos.ActualizacionProto> HistorialActualizaciones {
      get { return historialActualizaciones_; }
    }

    /// <summary>Field number for the "EstaHabilitado" field.</summary>
    public const int EstaHabilitadoFieldNumber = 11;
    private bool estaHabilitado_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool EstaHabilitado {
      get { return estaHabilitado_; }
      set {
        estaHabilitado_ = value;
      }
    }

    /// <summary>Field number for the "TieneDeudasActivas" field.</summary>
    public const int TieneDeudasActivasFieldNumber = 12;
    private bool tieneDeudasActivas_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool TieneDeudasActivas {
      get { return tieneDeudasActivas_; }
      set {
        tieneDeudasActivas_ = value;
      }
    }

    /// <summary>Field number for the "Productos" field.</summary>
    public const int ProductosFieldNumber = 13;
    private static readonly pb::FieldCodec<string> _repeated_productos_codec
        = pb::FieldCodec.ForString(106);
    private readonly pbc::RepeatedField<string> productos_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Productos {
      get { return productos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClienteProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClienteProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FechaActual != other.FechaActual) return false;
      if (Id != other.Id) return false;
      if (TipoIdentificacion != other.TipoIdentificacion) return false;
      if (NumeroIdentificacion != other.NumeroIdentificacion) return false;
      if (Nombres != other.Nombres) return false;
      if (Apellidos != other.Apellidos) return false;
      if (CorreoElectronico != other.CorreoElectronico) return false;
      if (FechaNacimiento != other.FechaNacimiento) return false;
      if (FechaCreacion != other.FechaCreacion) return false;
      if(!historialActualizaciones_.Equals(other.historialActualizaciones_)) return false;
      if (EstaHabilitado != other.EstaHabilitado) return false;
      if (TieneDeudasActivas != other.TieneDeudasActivas) return false;
      if(!productos_.Equals(other.productos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FechaActual.Length != 0) hash ^= FechaActual.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (TipoIdentificacion != 0) hash ^= TipoIdentificacion.GetHashCode();
      if (NumeroIdentificacion.Length != 0) hash ^= NumeroIdentificacion.GetHashCode();
      if (Nombres.Length != 0) hash ^= Nombres.GetHashCode();
      if (Apellidos.Length != 0) hash ^= Apellidos.GetHashCode();
      if (CorreoElectronico.Length != 0) hash ^= CorreoElectronico.GetHashCode();
      if (FechaNacimiento.Length != 0) hash ^= FechaNacimiento.GetHashCode();
      if (FechaCreacion.Length != 0) hash ^= FechaCreacion.GetHashCode();
      hash ^= historialActualizaciones_.GetHashCode();
      if (EstaHabilitado != false) hash ^= EstaHabilitado.GetHashCode();
      if (TieneDeudasActivas != false) hash ^= TieneDeudasActivas.GetHashCode();
      hash ^= productos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FechaActual.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FechaActual);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (TipoIdentificacion != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TipoIdentificacion);
      }
      if (NumeroIdentificacion.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NumeroIdentificacion);
      }
      if (Nombres.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Nombres);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Apellidos);
      }
      if (CorreoElectronico.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(CorreoElectronico);
      }
      if (FechaNacimiento.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(FechaNacimiento);
      }
      if (FechaCreacion.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(FechaCreacion);
      }
      historialActualizaciones_.WriteTo(output, _repeated_historialActualizaciones_codec);
      if (EstaHabilitado != false) {
        output.WriteRawTag(88);
        output.WriteBool(EstaHabilitado);
      }
      if (TieneDeudasActivas != false) {
        output.WriteRawTag(96);
        output.WriteBool(TieneDeudasActivas);
      }
      productos_.WriteTo(output, _repeated_productos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FechaActual.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FechaActual);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (TipoIdentificacion != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TipoIdentificacion);
      }
      if (NumeroIdentificacion.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NumeroIdentificacion);
      }
      if (Nombres.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Nombres);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Apellidos);
      }
      if (CorreoElectronico.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(CorreoElectronico);
      }
      if (FechaNacimiento.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(FechaNacimiento);
      }
      if (FechaCreacion.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(FechaCreacion);
      }
      historialActualizaciones_.WriteTo(ref output, _repeated_historialActualizaciones_codec);
      if (EstaHabilitado != false) {
        output.WriteRawTag(88);
        output.WriteBool(EstaHabilitado);
      }
      if (TieneDeudasActivas != false) {
        output.WriteRawTag(96);
        output.WriteBool(TieneDeudasActivas);
      }
      productos_.WriteTo(ref output, _repeated_productos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FechaActual.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FechaActual);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (TipoIdentificacion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TipoIdentificacion);
      }
      if (NumeroIdentificacion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeroIdentificacion);
      }
      if (Nombres.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nombres);
      }
      if (Apellidos.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Apellidos);
      }
      if (CorreoElectronico.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CorreoElectronico);
      }
      if (FechaNacimiento.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FechaNacimiento);
      }
      if (FechaCreacion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FechaCreacion);
      }
      size += historialActualizaciones_.CalculateSize(_repeated_historialActualizaciones_codec);
      if (EstaHabilitado != false) {
        size += 1 + 1;
      }
      if (TieneDeudasActivas != false) {
        size += 1 + 1;
      }
      size += productos_.CalculateSize(_repeated_productos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClienteProto other) {
      if (other == null) {
        return;
      }
      if (other.FechaActual.Length != 0) {
        FechaActual = other.FechaActual;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.TipoIdentificacion != 0) {
        TipoIdentificacion = other.TipoIdentificacion;
      }
      if (other.NumeroIdentificacion.Length != 0) {
        NumeroIdentificacion = other.NumeroIdentificacion;
      }
      if (other.Nombres.Length != 0) {
        Nombres = other.Nombres;
      }
      if (other.Apellidos.Length != 0) {
        Apellidos = other.Apellidos;
      }
      if (other.CorreoElectronico.Length != 0) {
        CorreoElectronico = other.CorreoElectronico;
      }
      if (other.FechaNacimiento.Length != 0) {
        FechaNacimiento = other.FechaNacimiento;
      }
      if (other.FechaCreacion.Length != 0) {
        FechaCreacion = other.FechaCreacion;
      }
      historialActualizaciones_.Add(other.historialActualizaciones_);
      if (other.EstaHabilitado != false) {
        EstaHabilitado = other.EstaHabilitado;
      }
      if (other.TieneDeudasActivas != false) {
        TieneDeudasActivas = other.TieneDeudasActivas;
      }
      productos_.Add(other.productos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FechaActual = input.ReadString();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 24: {
            TipoIdentificacion = input.ReadInt32();
            break;
          }
          case 34: {
            NumeroIdentificacion = input.ReadString();
            break;
          }
          case 42: {
            Nombres = input.ReadString();
            break;
          }
          case 50: {
            Apellidos = input.ReadString();
            break;
          }
          case 58: {
            CorreoElectronico = input.ReadString();
            break;
          }
          case 66: {
            FechaNacimiento = input.ReadString();
            break;
          }
          case 74: {
            FechaCreacion = input.ReadString();
            break;
          }
          case 82: {
            historialActualizaciones_.AddEntriesFrom(input, _repeated_historialActualizaciones_codec);
            break;
          }
          case 88: {
            EstaHabilitado = input.ReadBool();
            break;
          }
          case 96: {
            TieneDeudasActivas = input.ReadBool();
            break;
          }
          case 106: {
            productos_.AddEntriesFrom(input, _repeated_productos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FechaActual = input.ReadString();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 24: {
            TipoIdentificacion = input.ReadInt32();
            break;
          }
          case 34: {
            NumeroIdentificacion = input.ReadString();
            break;
          }
          case 42: {
            Nombres = input.ReadString();
            break;
          }
          case 50: {
            Apellidos = input.ReadString();
            break;
          }
          case 58: {
            CorreoElectronico = input.ReadString();
            break;
          }
          case 66: {
            FechaNacimiento = input.ReadString();
            break;
          }
          case 74: {
            FechaCreacion = input.ReadString();
            break;
          }
          case 82: {
            historialActualizaciones_.AddEntriesFrom(ref input, _repeated_historialActualizaciones_codec);
            break;
          }
          case 88: {
            EstaHabilitado = input.ReadBool();
            break;
          }
          case 96: {
            TieneDeudasActivas = input.ReadBool();
            break;
          }
          case 106: {
            productos_.AddEntriesFrom(ref input, _repeated_productos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CrearClienteProto : pb::IMessage<CrearClienteProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CrearClienteProto> _parser = new pb::MessageParser<CrearClienteProto>(() => new CrearClienteProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CrearClienteProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClienteReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearClienteProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearClienteProto(CrearClienteProto other) : this() {
      tipoIdentificacion_ = other.tipoIdentificacion_;
      numeroIdentificacion_ = other.numeroIdentificacion_;
      nombres_ = other.nombres_;
      apellidos_ = other.apellidos_;
      correoElectronico_ = other.correoElectronico_;
      fechaNacimiento_ = other.fechaNacimiento_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CrearClienteProto Clone() {
      return new CrearClienteProto(this);
    }

    /// <summary>Field number for the "TipoIdentificacion" field.</summary>
    public const int TipoIdentificacionFieldNumber = 1;
    private int tipoIdentificacion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TipoIdentificacion {
      get { return tipoIdentificacion_; }
      set {
        tipoIdentificacion_ = value;
      }
    }

    /// <summary>Field number for the "NumeroIdentificacion" field.</summary>
    public const int NumeroIdentificacionFieldNumber = 2;
    private string numeroIdentificacion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NumeroIdentificacion {
      get { return numeroIdentificacion_; }
      set {
        numeroIdentificacion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Nombres" field.</summary>
    public const int NombresFieldNumber = 3;
    private string nombres_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nombres {
      get { return nombres_; }
      set {
        nombres_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Apellidos" field.</summary>
    public const int ApellidosFieldNumber = 4;
    private string apellidos_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Apellidos {
      get { return apellidos_; }
      set {
        apellidos_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CorreoElectronico" field.</summary>
    public const int CorreoElectronicoFieldNumber = 5;
    private string correoElectronico_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CorreoElectronico {
      get { return correoElectronico_; }
      set {
        correoElectronico_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "FechaNacimiento" field.</summary>
    public const int FechaNacimientoFieldNumber = 6;
    private string fechaNacimiento_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FechaNacimiento {
      get { return fechaNacimiento_; }
      set {
        fechaNacimiento_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CrearClienteProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CrearClienteProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TipoIdentificacion != other.TipoIdentificacion) return false;
      if (NumeroIdentificacion != other.NumeroIdentificacion) return false;
      if (Nombres != other.Nombres) return false;
      if (Apellidos != other.Apellidos) return false;
      if (CorreoElectronico != other.CorreoElectronico) return false;
      if (FechaNacimiento != other.FechaNacimiento) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TipoIdentificacion != 0) hash ^= TipoIdentificacion.GetHashCode();
      if (NumeroIdentificacion.Length != 0) hash ^= NumeroIdentificacion.GetHashCode();
      if (Nombres.Length != 0) hash ^= Nombres.GetHashCode();
      if (Apellidos.Length != 0) hash ^= Apellidos.GetHashCode();
      if (CorreoElectronico.Length != 0) hash ^= CorreoElectronico.GetHashCode();
      if (FechaNacimiento.Length != 0) hash ^= FechaNacimiento.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TipoIdentificacion != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TipoIdentificacion);
      }
      if (NumeroIdentificacion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeroIdentificacion);
      }
      if (Nombres.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nombres);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Apellidos);
      }
      if (CorreoElectronico.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CorreoElectronico);
      }
      if (FechaNacimiento.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FechaNacimiento);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TipoIdentificacion != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TipoIdentificacion);
      }
      if (NumeroIdentificacion.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NumeroIdentificacion);
      }
      if (Nombres.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nombres);
      }
      if (Apellidos.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Apellidos);
      }
      if (CorreoElectronico.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CorreoElectronico);
      }
      if (FechaNacimiento.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FechaNacimiento);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TipoIdentificacion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TipoIdentificacion);
      }
      if (NumeroIdentificacion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeroIdentificacion);
      }
      if (Nombres.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nombres);
      }
      if (Apellidos.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Apellidos);
      }
      if (CorreoElectronico.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CorreoElectronico);
      }
      if (FechaNacimiento.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FechaNacimiento);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CrearClienteProto other) {
      if (other == null) {
        return;
      }
      if (other.TipoIdentificacion != 0) {
        TipoIdentificacion = other.TipoIdentificacion;
      }
      if (other.NumeroIdentificacion.Length != 0) {
        NumeroIdentificacion = other.NumeroIdentificacion;
      }
      if (other.Nombres.Length != 0) {
        Nombres = other.Nombres;
      }
      if (other.Apellidos.Length != 0) {
        Apellidos = other.Apellidos;
      }
      if (other.CorreoElectronico.Length != 0) {
        CorreoElectronico = other.CorreoElectronico;
      }
      if (other.FechaNacimiento.Length != 0) {
        FechaNacimiento = other.FechaNacimiento;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TipoIdentificacion = input.ReadInt32();
            break;
          }
          case 18: {
            NumeroIdentificacion = input.ReadString();
            break;
          }
          case 26: {
            Nombres = input.ReadString();
            break;
          }
          case 34: {
            Apellidos = input.ReadString();
            break;
          }
          case 42: {
            CorreoElectronico = input.ReadString();
            break;
          }
          case 50: {
            FechaNacimiento = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TipoIdentificacion = input.ReadInt32();
            break;
          }
          case 18: {
            NumeroIdentificacion = input.ReadString();
            break;
          }
          case 26: {
            Nombres = input.ReadString();
            break;
          }
          case 34: {
            Apellidos = input.ReadString();
            break;
          }
          case 42: {
            CorreoElectronico = input.ReadString();
            break;
          }
          case 50: {
            FechaNacimiento = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ActualizacionProto : pb::IMessage<ActualizacionProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActualizacionProto> _parser = new pb::MessageParser<ActualizacionProto>(() => new ActualizacionProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActualizacionProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EntryPoints.GRPc.Protos.ClienteReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActualizacionProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActualizacionProto(ActualizacionProto other) : this() {
      tipoActualizacion_ = other.tipoActualizacion_;
      usuarioModificacion_ = other.usuarioModificacion_ != null ? other.usuarioModificacion_.Clone() : null;
      fecha_ = other.fecha_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActualizacionProto Clone() {
      return new ActualizacionProto(this);
    }

    /// <summary>Field number for the "tipoActualizacion" field.</summary>
    public const int TipoActualizacionFieldNumber = 1;
    private int tipoActualizacion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TipoActualizacion {
      get { return tipoActualizacion_; }
      set {
        tipoActualizacion_ = value;
      }
    }

    /// <summary>Field number for the "usuarioModificacion" field.</summary>
    public const int UsuarioModificacionFieldNumber = 2;
    private global::EntryPoints.GRPc.Protos.UsuarioProto usuarioModificacion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EntryPoints.GRPc.Protos.UsuarioProto UsuarioModificacion {
      get { return usuarioModificacion_; }
      set {
        usuarioModificacion_ = value;
      }
    }

    /// <summary>Field number for the "fecha" field.</summary>
    public const int FechaFieldNumber = 3;
    private string fecha_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Fecha {
      get { return fecha_; }
      set {
        fecha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ActualizacionProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ActualizacionProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TipoActualizacion != other.TipoActualizacion) return false;
      if (!object.Equals(UsuarioModificacion, other.UsuarioModificacion)) return false;
      if (Fecha != other.Fecha) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TipoActualizacion != 0) hash ^= TipoActualizacion.GetHashCode();
      if (usuarioModificacion_ != null) hash ^= UsuarioModificacion.GetHashCode();
      if (Fecha.Length != 0) hash ^= Fecha.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TipoActualizacion != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TipoActualizacion);
      }
      if (usuarioModificacion_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UsuarioModificacion);
      }
      if (Fecha.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Fecha);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TipoActualizacion != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TipoActualizacion);
      }
      if (usuarioModificacion_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(UsuarioModificacion);
      }
      if (Fecha.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Fecha);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TipoActualizacion != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TipoActualizacion);
      }
      if (usuarioModificacion_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UsuarioModificacion);
      }
      if (Fecha.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Fecha);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ActualizacionProto other) {
      if (other == null) {
        return;
      }
      if (other.TipoActualizacion != 0) {
        TipoActualizacion = other.TipoActualizacion;
      }
      if (other.usuarioModificacion_ != null) {
        if (usuarioModificacion_ == null) {
          UsuarioModificacion = new global::EntryPoints.GRPc.Protos.UsuarioProto();
        }
        UsuarioModificacion.MergeFrom(other.UsuarioModificacion);
      }
      if (other.Fecha.Length != 0) {
        Fecha = other.Fecha;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TipoActualizacion = input.ReadInt32();
            break;
          }
          case 18: {
            if (usuarioModificacion_ == null) {
              UsuarioModificacion = new global::EntryPoints.GRPc.Protos.UsuarioProto();
            }
            input.ReadMessage(UsuarioModificacion);
            break;
          }
          case 26: {
            Fecha = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TipoActualizacion = input.ReadInt32();
            break;
          }
          case 18: {
            if (usuarioModificacion_ == null) {
              UsuarioModificacion = new global::EntryPoints.GRPc.Protos.UsuarioProto();
            }
            input.ReadMessage(UsuarioModificacion);
            break;
          }
          case 26: {
            Fecha = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
