// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/Cliente.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace EntryPoints.GRPc.Protos {
  /// <summary>
  /// Services
  /// </summary>
  public static partial class ClienteServices
  {
    static readonly string __ServiceName = "clientes.ClienteServices";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.GRPc.Protos.CrearUsuarioRequest> __Marshaller_clientes_CrearUsuarioRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.GRPc.Protos.CrearUsuarioRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.GRPc.Protos.UsuarioProto> __Marshaller_clientes_UsuarioProto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.GRPc.Protos.UsuarioProto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.GRPc.Protos.ClienteCrearRequest> __Marshaller_clientes_ClienteCrearRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.GRPc.Protos.ClienteCrearRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.GRPc.Protos.ClienteProto> __Marshaller_clientes_ClienteProto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.GRPc.Protos.ClienteProto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.GRPc.Protos.Empty> __Marshaller_clientes_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.GRPc.Protos.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::EntryPoints.GRPc.Protos.RespuestaListaClientes> __Marshaller_clientes_RespuestaListaClientes = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::EntryPoints.GRPc.Protos.RespuestaListaClientes.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.GRPc.Protos.CrearUsuarioRequest, global::EntryPoints.GRPc.Protos.UsuarioProto> __Method_CrearUsuario = new grpc::Method<global::EntryPoints.GRPc.Protos.CrearUsuarioRequest, global::EntryPoints.GRPc.Protos.UsuarioProto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CrearUsuario",
        __Marshaller_clientes_CrearUsuarioRequest,
        __Marshaller_clientes_UsuarioProto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.GRPc.Protos.ClienteCrearRequest, global::EntryPoints.GRPc.Protos.ClienteProto> __Method_CrearCliente = new grpc::Method<global::EntryPoints.GRPc.Protos.ClienteCrearRequest, global::EntryPoints.GRPc.Protos.ClienteProto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CrearCliente",
        __Marshaller_clientes_ClienteCrearRequest,
        __Marshaller_clientes_ClienteProto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::EntryPoints.GRPc.Protos.Empty, global::EntryPoints.GRPc.Protos.RespuestaListaClientes> __Method_ObtenerTodosLosClientes = new grpc::Method<global::EntryPoints.GRPc.Protos.Empty, global::EntryPoints.GRPc.Protos.RespuestaListaClientes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ObtenerTodosLosClientes",
        __Marshaller_clientes_Empty,
        __Marshaller_clientes_RespuestaListaClientes);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EntryPoints.GRPc.Protos.ClienteReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ClienteServices</summary>
    [grpc::BindServiceMethod(typeof(ClienteServices), "BindService")]
    public abstract partial class ClienteServicesBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.GRPc.Protos.UsuarioProto> CrearUsuario(global::EntryPoints.GRPc.Protos.CrearUsuarioRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.GRPc.Protos.ClienteProto> CrearCliente(global::EntryPoints.GRPc.Protos.ClienteCrearRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::EntryPoints.GRPc.Protos.RespuestaListaClientes> ObtenerTodosLosClientes(global::EntryPoints.GRPc.Protos.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ClienteServices</summary>
    public partial class ClienteServicesClient : grpc::ClientBase<ClienteServicesClient>
    {
      /// <summary>Creates a new client for ClienteServices</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ClienteServicesClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ClienteServices that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ClienteServicesClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ClienteServicesClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ClienteServicesClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPc.Protos.UsuarioProto CrearUsuario(global::EntryPoints.GRPc.Protos.CrearUsuarioRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CrearUsuario(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPc.Protos.UsuarioProto CrearUsuario(global::EntryPoints.GRPc.Protos.CrearUsuarioRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CrearUsuario, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPc.Protos.UsuarioProto> CrearUsuarioAsync(global::EntryPoints.GRPc.Protos.CrearUsuarioRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CrearUsuarioAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPc.Protos.UsuarioProto> CrearUsuarioAsync(global::EntryPoints.GRPc.Protos.CrearUsuarioRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CrearUsuario, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPc.Protos.ClienteProto CrearCliente(global::EntryPoints.GRPc.Protos.ClienteCrearRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CrearCliente(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPc.Protos.ClienteProto CrearCliente(global::EntryPoints.GRPc.Protos.ClienteCrearRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CrearCliente, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPc.Protos.ClienteProto> CrearClienteAsync(global::EntryPoints.GRPc.Protos.ClienteCrearRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CrearClienteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPc.Protos.ClienteProto> CrearClienteAsync(global::EntryPoints.GRPc.Protos.ClienteCrearRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CrearCliente, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPc.Protos.RespuestaListaClientes ObtenerTodosLosClientes(global::EntryPoints.GRPc.Protos.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerTodosLosClientes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::EntryPoints.GRPc.Protos.RespuestaListaClientes ObtenerTodosLosClientes(global::EntryPoints.GRPc.Protos.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ObtenerTodosLosClientes, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPc.Protos.RespuestaListaClientes> ObtenerTodosLosClientesAsync(global::EntryPoints.GRPc.Protos.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ObtenerTodosLosClientesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::EntryPoints.GRPc.Protos.RespuestaListaClientes> ObtenerTodosLosClientesAsync(global::EntryPoints.GRPc.Protos.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ObtenerTodosLosClientes, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ClienteServicesClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ClienteServicesClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ClienteServicesBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CrearUsuario, serviceImpl.CrearUsuario)
          .AddMethod(__Method_CrearCliente, serviceImpl.CrearCliente)
          .AddMethod(__Method_ObtenerTodosLosClientes, serviceImpl.ObtenerTodosLosClientes).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ClienteServicesBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CrearUsuario, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.GRPc.Protos.CrearUsuarioRequest, global::EntryPoints.GRPc.Protos.UsuarioProto>(serviceImpl.CrearUsuario));
      serviceBinder.AddMethod(__Method_CrearCliente, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.GRPc.Protos.ClienteCrearRequest, global::EntryPoints.GRPc.Protos.ClienteProto>(serviceImpl.CrearCliente));
      serviceBinder.AddMethod(__Method_ObtenerTodosLosClientes, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EntryPoints.GRPc.Protos.Empty, global::EntryPoints.GRPc.Protos.RespuestaListaClientes>(serviceImpl.ObtenerTodosLosClientes));
    }

  }
}
#endregion
